CineTech/CineTech/Models/Film.cs
using Newtonsoft.Json.Serialization;
using System.ComponentModel.DataAnnotations;

namespace CineTech.Models
{
    public class Film
    {
        [Key]
        public int id { get; set; }
        [Required]
        [Display(Name = "Naziv Filma:")]
        public String naziv { get; set; }
        [Required]
        [Display(Name = "Naslovna slika:")]
        public String naslovnaSlika { get; set; }
        [Required]
        [MaxLength(500)]
        [Display(Name = "Opis radnje:")]
        public String opis { get; set; }
        [Required]
        [Display(Name = "Redatelj:")]
        public String redatelj { get; set; }
        [Required]
        [Display(Name = "Glumci:")]
        public String glumci { get; set; }
        [ValidateDate]
        [Required]
        [Display(Name = "Relese Date:")]
        [DataType(DataType.Date)]

        public DateTime releseDate { get; set; }
        [Required]
        [Display(Name = "Trailer:")]
        public String trailer { get; set; }
        [Required]
        [EnumDataType(typeof(StatusPrikazivanja))]
        [Display(Name = "Status prikazivanja:")]
        public StatusPrikazivanja StatusPrikazivanja { get; set; }
        public Film() { }
}
}

CineTech/CineTech/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CineTech.Data;
using CineTech.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Threading.Tasks;
using Microsoft.DotNet.Scaffolding.Shared.CodeModifier.CodeChange;
using RestSharp;
using Newtonsoft.Json.Linq;
using CineTech.Services;
using System.Collections;

namespace CineTech.Controllers
{
    public class FilmsController : Controller
    {
        private readonly ApplicationDbContext _context;
       // private readonly MovieService movieService;

        public FilmsController(ApplicationDbContext context /*MovieService movieService*/)
        {
            _context = context;
           // this.movieService = movieService;
        }
        // GET: Films
        [Authorize(Roles = "Administrator")]
        public IActionResult AdminIndex()
        {

            return View();
        }
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> AdminFilmovi()
        {
            var filmovi = await _context.Film.OrderBy(f => f.StatusPrikazivanja == StatusPrikazivanja.Aktuelan ? 1 :
                      f.StatusPrikazivanja == StatusPrikazivanja.UNajavi ? 2 : 3)
            .ToListAsync();
            return View(filmovi);
        }

        // GET: Films/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film
                .FirstOrDefaultAsync(m => m.id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> AdminDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film
                .FirstOrDefaultAsync(m => m.id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: Films/Create
        [Authorize(Roles = "Administrator")]
        public  IActionResult Create()
        {
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("id,naziv,naslovnaSlika,opis,redatelj,glumci,releseDate,trailer,StatusPrikazivanja")] Film film)
        {
            if (ModelState.IsValid)
            {
                _context.Add(film);
                await _context.SaveChangesAsync();
                return RedirectToAction("Create","ZanroviFilmas", new { id = film.id });
            }
            return View(film);
        }
        public IActionResult OdabirZanra(int id)
        {
            // You can fetch the film using the id if necessary
            var film = _context.Film.Find(id);
            var zanrovi = _context.ZanroviFilma.ToList();
            ViewBag.zanrovi = zanrovi;
            // Pass the film or film ID to the view as needed
            return View();
        }
        // GET: Films/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("id,naziv,naslovnaSlika,opis,redatelj,glumci,releseDate,trailer,StatusPrikazivanja")] Film film)
        {
            if (id != film.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(AdminFilmovi));
            }
            return View(film);
        }

        // GET: Films/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film
                .FirstOrDefaultAsync(m => m.id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var film = await _context.Film.FindAsync(id);
            if (film != null)
            {
                _context.Film.Remove(film);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(AdminFilmovi));
        }

       public async Task<IActionResult> NajavljeniFilmovi()
        {
             var najavljeniFilmovi = await _context.Film
            .Where(f => f.StatusPrikazivanja == StatusPrikazivanja.UNajavi)
            .ToListAsync();
            var filmGenres = new Dictionary<int, List<Zanr>>();

            foreach (var film in najavljeniFilmovi)
            {
                var genres = await _context.ZanroviFilma
                    .Where(z => z.idFilma == film.id)
                    .Select(z => z.zanrFilma)
                    .ToListAsync();
                filmGenres[film.id] = genres;
            }
            ViewBag.FilmGenres = filmGenres;

            return View(najavljeniFilmovi);
        }
        private bool FilmExists(int id)
        {
            return _context.Film.Any(e => e.id == id);
        }
        public IActionResult NajgledanijiFilmovi()
        {
            var prosjecneOcjenePoFilmu = _context.Ocjena
                .GroupBy(o => o.FilmId)
                .Select(g => new
                {
                    FilmId = g.Key,
                    ProsjecnaOcjena = g.Average(o => o.ocjenaFilma)
                })
                .ToList();

            prosjecneOcjenePoFilmu = prosjecneOcjenePoFilmu.OrderByDescending(o => o.ProsjecnaOcjena).ToList();

            var najgledanijiFilmoviIds = prosjecneOcjenePoFilmu.Take(5).Select(o => o.FilmId).ToList();

            var najgledanijiFilmovi = _context.Film.Where(f => najgledanijiFilmoviIds.Contains(f.id)).ToList();
            

            if (najgledanijiFilmovi == null)
            {
                return View(new List<Film>());
            }
            najgledanijiFilmovi = najgledanijiFilmovi.OrderBy(f => najgledanijiFilmoviIds.IndexOf(f.id)).ToList();
            return View(najgledanijiFilmovi.AsEnumerable());
        }
        public async Task<IActionResult> NajgledanijiFilmoviUSvijetu()
        {
            var apiKey = "770d50d3bf1a676bc83f8fca0279e015";
            var tmdbService = new TmdbService(apiKey);

            var popularMovies = await tmdbService.GetPopularMoviesAsync();
            var topRatedMovies = await tmdbService.GetTopRatedMoviesAsync();

           /* Console.WriteLine("Popular Movies:");
            foreach (var movie in popularMovies.Results)
            {


                Console.WriteLine($"{movie.Title} (Rating: {movie.VoteAverage})");
            }

            Console.WriteLine("\nTop Rated Movies:");
            foreach (var movie in topRatedMovies.Results)
            {
                Console.WriteLine($"{movie.Title} (Rating: {movie.VoteAverage})");
            }*/
            

            return View(popularMovies.Results);
        }
    }
}

CineTech/CineTech/Views/Films/AdminDetails.cshtml
@model CineTech.Models.Film

@{
    ViewData["Title"] = "AdminDetails";
}

<h1 class="text-center my-4">Detalji filma</h1>

<div class="container">
    <h4 class="mb-4">Film</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3 font-weight-bold">
            @Html.DisplayNameFor(model => model.naziv)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.naziv)
        </dd>

        <dt class="col-sm-3 font-weight-bold">
            Naslovna slika
        </dt>
        <dd class="col-sm-9">
            <img src="@Model.naslovnaSlika" class="img-fluid img-thumbnail" alt="Naslovna slika filma" />
        </dd>

        <dt class="col-sm-3 font-weight-bold">
            @Html.DisplayNameFor(model => model.opis)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.opis)
        </dd>

        <dt class="col-sm-3 font-weight-bold">
            @Html.DisplayNameFor(model => model.redatelj)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.redatelj)
        </dd>

        <dt class="col-sm-3 font-weight-bold">
            @Html.DisplayNameFor(model => model.glumci)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.glumci)
        </dd>

        <dt class="col-sm-3 font-weight-bold">
            @Html.DisplayNameFor(model => model.releseDate)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.releseDate)
        </dd>

        <dt class="col-sm-3 font-weight-bold">
            @Html.DisplayNameFor(model => model.trailer)
        </dt>
        <dd class="col-sm-9">
            <a href="@Model.trailer" target="_blank" class="btn btn-outline-info">Pogledaj trailer</a>
        </dd>

        <dt class="col-sm-3 font-weight-bold">
            @Html.DisplayNameFor(model => model.StatusPrikazivanja)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.StatusPrikazivanja)
        </dd>
    </dl>
</div>
<div class="text-center mt-4">
    @if (User.IsInRole("Administrator"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.id" class="btn btn-warning mx-2">Izmijeni</a>
    }
    <a asp-controller="Films" asp-action="AdminFilmovi" class="btn btn-secondary mx-2">Nazad</a>
</div>

CineTech/CineTech/Views/Films/AdminFilmovi.cshtml
@model IEnumerable<CineTech.Models.Film>

@{
    ViewData["Title"] = "AdminFilmovi";
}

<h1 class="text-center my-4">Dodavanje, brisanje i izmjena informacija o filmovima</h1>

<p>
    @if (User.IsInRole("Administrator"))
    {
        <a asp-action="Create" class="btn btn-success mb-3">Dodaj Film</a>
    }
</p>
<table class="table table-bordered table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.naslovnaSlika)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.opis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.redatelj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.glumci)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.releseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.trailer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusPrikazivanja)
            </th>
            <th>Akcije</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.naziv)
                </td>
                <td>
                    <img src="@item.naslovnaSlika" class="img-thumbnail" style="max-width: 100px;" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.opis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.redatelj)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.glumci)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.releseDate)
                </td>
                <td>
                    <a href="@item.trailer" target="_blank" class="btn btn-outline-info btn-sm">Trailer</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusPrikazivanja)
                </td>
                <td>
                    @if (User.IsInRole("Administrator"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.id" class="btn btn-warning btn-sm">Izmjeni</a>
                        <a asp-action="Delete" asp-route-id="@item.id" class="btn btn-danger btn-sm">Obriši</a>
                    }
                    <a asp-action="AdminDetails" asp-route-id="@item.id" class="btn btn-primary btn-sm">Detalji</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="text-center">
    <a asp-action="AdminIndex" class="btn btn-secondary mt-3">Nazad</a>
</div>

CineTech/CineTech/Views/Films/AdminIndex.cshtml
@model IEnumerable<CineTech.Models.Film>

@{
    ViewData["Title"] = "AdminIndex";
}

<h1 class="text-center my-4">Administratorska kontrolna ploča</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm border-0 rounded-lg">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <a asp-action="AdminFilmovi" class="btn btn-primary btn-block">Panel za filmove</a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a asp-controller="KinoSalas" asp-action="Index" class="btn btn-primary btn-block">Panel za Kino sale</a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a asp-controller="Projekcijas" asp-action="Index" class="btn btn-primary btn-block">Panel za Projekcije</a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a asp-controller="Ocjenas" asp-action="Index" class="btn btn-primary btn-block">Panel ocjena</a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a asp-controller="Home" asp-action="SviKorisnici" class="btn btn-primary btn-block">Panel korisnika</a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a asp-controller="ZanroviFilmas" asp-action="Index" class="btn btn-primary btn-block">Panel zanrova za filmove</a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a asp-controller="Home" asp-action="StatistikaView" class="btn btn-primary btn-block">Panel za statistiku</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CineTech/CineTech/Views/Films/Create.cshtml
@model CineTech.Models.Film

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center my-4">Dodavanje filma</h1>

<h4 class="mb-4">Film</h4>
<hr />
<div class="row justify-content-center">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="naziv" class="control-label"></label>
                <input asp-for="naziv" class="form-control" />
                <span asp-validation-for="naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="naslovnaSlika" class="control-label"></label>
                <input asp-for="naslovnaSlika" class="form-control" />
                <span asp-validation-for="naslovnaSlika" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="opis" class="control-label"></label>
                <textarea asp-for="opis" class="form-control"></textarea>
                <span asp-validation-for="opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="redatelj" class="control-label"></label>
                <input asp-for="redatelj" class="form-control" />
                <span asp-validation-for="redatelj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="glumci" class="control-label"></label>
                <input asp-for="glumci" class="form-control" />
                <span asp-validation-for="glumci" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="releseDate" class="control-label"></label>
                <input asp-for="releseDate" class="form-control" />
                <span asp-validation-for="releseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="trailer" class="control-label"></label>
                <input asp-for="trailer" class="form-control" />
                <span asp-validation-for="trailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusPrikazivanja" class="control-label"></label>
                <select asp-for="StatusPrikazivanja" class="form-control" asp-items="Html.GetEnumSelectList<StatusPrikazivanja>()"></select>
                <span asp-validation-for="StatusPrikazivanja" class="text-danger"></span>
            </div>
            <div class="form-group text-center">
                <input type="submit" value="Dodaj film" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div class="text-center mt-4">
    <a asp-action="AdminFilmovi" class="btn btn-secondary">Nazad</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CineTech/CineTech/Views/Films/Delete.cshtml
@model CineTech.Models.Film

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-center my-4">Obriši Film</h1>

<h3 class="text-center text-danger">Da li ste sigurni da želite obrisati ovaj film?</h3>

<div class="row justify-content-center">
    <div class="col-md-8">
        <h4 class="mb-4">Film</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.naziv)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.naziv)
            </dd>
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.naslovnaSlika)
            </dt>
            <dd class="col-sm-9">
                <img src="@Model.naslovnaSlika" class="img-thumbnail" alt="Naslovna Slika" />
            </dd>
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.opis)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.opis)
            </dd>
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.redatelj)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.redatelj)
            </dd>
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.glumci)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.glumci)
            </dd>
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.releseDate)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.releseDate)
            </dd>
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.trailer)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.trailer)
            </dd>
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.StatusPrikazivanja)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.StatusPrikazivanja)
            </dd>
        </dl>
        <form asp-action="Delete" class="mt-4">
            <input type="hidden" asp-for="id" />
            <div class="form-group text-center">
                <input type="submit" value="Obriši" class="btn btn-danger" /> |
                <a asp-action="AdminFilmovi" class="btn btn-secondary">Nazad</a>
            </div>
        </form>
    </div>
</div>

CineTech/CineTech/Views/Films/NajavljeniFilmovi.cshtml
@model IEnumerable<CineTech.Models.Film>

@{
    ViewData["Title"] = "NajavljeniFilmovi";
    var filmGenres = ViewBag.FilmGenres as Dictionary<int, List<Zanr>>;
}

<h1 class="text-center my-4">Filmovi u najavi</h1>

<div class="container">
    <div class="row">
        @foreach (var film in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow-sm">
                    <a asp-controller="Films" asp-action="Details" asp-route-id="@film.id">
                        <img class="card-img-top" src="@film.naslovnaSlika" alt="@film.naziv" />
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">@film.naziv</h5>
                        <h6 class="card-subtitle mb-2 text-muted">@film.redatelj</h6>
                        <p class="card-text">
                            <strong>Žanr:</strong>
                            @if (filmGenres != null && filmGenres.ContainsKey(film.id))
                            {
                                @string.Join(", ", filmGenres[film.id])
                            }
                            else
                            {
                                <span>N/A</span>
                            }
                            <br />
                            <strong>Release date:</strong> @film.releseDate.ToString("MM/dd/yyyy")<br />
                            <strong>Glumci:</strong> @film.glumci<br />
                            <strong>Opis:</strong> @film.opis
                        </p>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <a href="@film.trailer" class="btn btn-primary">Pogledaj trailer</a>
                        @if (User.IsInRole("Administrator") || User.IsInRole("Korisnik"))
                        {
                            <a asp-controller="Notifikacijas" asp-action="Create" asp-route-id="@film.id" class="btn btn-secondary">Postavi notifikaciju</a>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

CineTech/CineTech/Views/Films/NajgledanijiFilmovi.cshtml
@using Microsoft.AspNetCore.Identity
@using CineTech.Data;

@inject UserManager<IdentityUser> UserManager
@inject SignInManager<IdentityUser> SignInManager
@inject ApplicationDbContext _context;
@model IEnumerable<CineTech.Models.Film>

<h1 class="text-center my-4">Najgledaniji filmovi</h1>

<center style="margin-bottom:10px">
    <a asp-controller="Films" asp-action="NajgledanijiFilmoviUSvijetu" class="btn btn-secondary">
        Najpopularniji filmovi u svijetu
    </a>
</center>

<div class="container">
    <div class="row">
        @foreach (var film in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow-sm">
                    <a asp-controller="Films" asp-action="Details" asp-route-id="@film.id">
                        <img class="card-img-top" src="@film.naslovnaSlika" alt="@film.naziv" />
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">@film.naziv</h5>
                        @{
                            var ocjeneFilma = _context.Ocjena.Where(o => o.FilmId == film.id).ToList();
                            var prosjecnaOcjena = ocjeneFilma.Any() ? ocjeneFilma.Average(o => o.ocjenaFilma) : 0;
                        }
                        <p class="card-text">Prosjecna ocjena: @prosjecnaOcjena.ToString("0.00")</p>
                    </div>
                    <div class="card-footer">
                        <a href="@film.trailer" class="btn btn-primary" target="_blank">Pogledaj trailer</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

CineTech/CineTech/Views/Films/NajgledanijiFilmoviUSvijetu.cshtml
@model IEnumerable<CineTech.Models.MovieTMDb>
@{
    ViewData["Title"] = "NajgledanijiFilmoviUSvijetu";
}
<center>
    <h1>Trenutno napopularniji filmovi u svijetu by</h1>
    <img style="margin:10px" src="https://www.themoviedb.org/assets/2/v4/logos/v2/blue_long_1-8ba2ac31f354005783fab473602c34c3f4fd207150182061e425d366e4f34596.svg" />
</center>
<div class="row">
    @foreach (var film in Model)
    {
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img class="card-img-top" src="@($"https://image.tmdb.org/t/p/w342{film.Poster_Path}")" alt="@film.Title" />
                <div class="card-body">
                    <h5 class="card-title">@film.Title</h5>
                    <p class="card-text">
                        <strong>Opis:</strong> @film.Overview
                    </p>
                </div>
            </div>
        </div>
    }
</div>